name: parawarga_apps
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #https://pub.dev/packages/get
  get: ^4.6.6

  #https://pub.dev/packages/floor
  floor: ^1.4.2

  #https://pub.dev/packages/sqflite
  sqflite: ^2.3.0

  #https://pub.dev/packages/path_provider
  path_provider: ^2.0.4

  #https://pub.dev/packages/intl
  intl: ^0.19.0

  #https://pub.dev/packages/equatable
  equatable: ^2.0.5

  #https://pub.dev/packages/image_picker
  image_picker: ^1.0.5

  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.0

  #https://pub.dev/packages/badges
  badges: ^3.1.2

  #https://pub.dev/packages/flowder
  flowder:
    git:
      url: https://github.com/Harsh223/flowder.git

  #https://pub.dev/packages/permission_handler
  permission_handler: ^11.3.0

  #https://pub.dev/packages/open_filex
  open_filex: ^4.4.0

  #https://pub.dev/packages/colorful_progress_indicators
  colorful_progress_indicators: ^1.0.2

  #https://pub.dev/packages/iconsax
  iconsax: ^0.0.8

  #https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.1.1

  #https://pub.dev/packages/device_info_plus
  device_info_plus: ^11.2.0

  #https://pub.dev/packages/jwt_decoder
  jwt_decoder: ^2.0.1

  #https://pub.dev/packages/mime
  mime: ^1.0.6

  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.2

  #https://pub.dev/packages/timeline_tile
  timeline_tile: ^2.0.0

  #https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.2.1

  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  #https://pub.dev/packages/build_runner
  build_runner: ^2.4.7

  #https://pub.dev/packages/floor_generator
  floor_generator: 1.4.2

  #https://pub.dev/packages/flutter_fortune_wheel
  flutter_fortune_wheel: ^1.3.2

  #https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - .env #root project .env
    - assets/
    - assets/fonts/
    - assets/fonts/bariol/
    - assets/images/
    - assets/images/logo/
    - assets/images/icon/
    - assets/images/background/

  fonts:
    - family: bariol
      fonts:
        - asset: assets/fonts/bariol/Bariol.ttf
        - asset: assets/fonts/bariol/Bariol-Bold.ttf
          weight: 700
        - asset: assets/fonts/bariol/Bariol-Light.ttf
          weight: 300

    - family: evolvesans
      fonts:
        - asset: assets/fonts/Evolvesans.otf

    - family: quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.otf
          weight: 700

    - family: rodina
      fonts:
        - asset: assets/fonts/Rodina.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/img_logo_icon.png"
  adaptive_icon_foreground: "assets/images/logo/img_logo_icon.png"
  adaptive_icon_background: "#04454d"
