Map<int, String> migrationScripts = {
  1: '''CREATE TABLE IF NOT EXISTS `profile` (
          `username` TEXT NOT NULL, 
          `nik` TEXT, 
          `password` TEXT, 
          `name` TEXT, 
          `email` TEXT, 
          `direktorat` TEXT, 
          `departemen` TEXT, 
          `divisi` TEXT, 
          `job_function` TEXT, 
          `isUpdateApk` INTEGER, 
          `status` INTEGER, 
          `statusKirim` INTEGER, 
          `createdAt` TEXT, 
          `updatedAt` TEXT, 
          PRIMARY KEY (`username`))''',
  2: '''ALTER TABLE `profile` ADD `user_id` INTEGER''',
  3: '''CREATE TABLE IF NOT EXISTS `pengaturan_autocode` (
          `code` TEXT NOT NULL, 
          `value` TEXT, 
          `count` TEXT, 
          `keterangan` TEXT,
          `status` INTEGER, 
          `statusKirim` INTEGER, 
          `createdAt` TEXT, 
          `updatedAt` TEXT, 
          PRIMARY KEY (`code`))''',
};